/**
 * Regenerates docs/COVERAGE.md from the content files so the checklist never drifts.
 * Usage: npm run coverage:report
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { conceptStatus, coverage } from '../src/logic/curriculum';
import { loadContent, ROOT } from './load-content';

const { curriculum, tracks, reviewer, lessons } = loadContent();
const L: string[] = [];
const p = (s = '') => L.push(s);
const ICON = { complete: '✅ complete', 'complete-needs-review': '🟡 complete — requires review', draft: '🟠 draft (incomplete)', pending: '⬜ pending' } as const;

p('# Curriculum coverage checklist');
p();
p('_Generated by `npm run coverage:report` from /content. Do not edit by hand._');
p();
p('## Source reviewer');
p();
p(`- Received: **${reviewer.received ? 'yes' : 'NO'}**`);
p(`- Pages accessible: ${reviewer.pagesAccessible ?? 'none'}`);
p(`- ${reviewer.statement}`);
p();
if (reviewer.chapters.length) {
  p('| Chapter | Pages | Status |');
  p('|---|---|---|');
  reviewer.chapters.forEach((c) => p(`| ${c.title} | ${c.pages} | ${c.status} |`));
} else p('No reviewer chapters inventoried yet (reviewer not received).');
p();
p('## Curriculum inventory');
p();
p(`- Provenance: **${curriculum.provenance.status}** — ${curriculum.provenance.statement}`);
p();
p('Legend: ✅ complete lesson · 🟡 complete lesson that still requires accuracy/expert review · 🟠 draft that fails the completeness check · ⬜ no lesson yet. Titles, placeholders and drafts are never counted as complete.');
p();
const all = coverage(curriculum, lessons, 'both');
const tot = all.reduce((a, d) => ({ total: a.total + d.total, complete: a.complete + d.complete, review: a.review + d.needsReview, draft: a.draft + d.draft, mapped: a.mapped + d.mappedToReviewer }), { total: 0, complete: 0, review: 0, draft: 0, mapped: 0 });
p(`**Totals:** ${tot.complete}/${tot.total} concepts have a complete lesson (${tot.review} of those require review); ${tot.draft} draft; ${tot.total - tot.complete - tot.draft} pending; ${tot.mapped} mapped to reviewer pages.`);
p();
p('| Domain | Concepts | Complete | Requires review | Draft | Pending | Mapped to reviewer |');
p('|---|---|---|---|---|---|---|');
all.forEach((d) => p(`| ${d.domain.title} | ${d.total} | ${d.complete} | ${d.needsReview} | ${d.draft} | ${d.pending} | ${d.mappedToReviewer} |`));
p();
for (const d of [...curriculum.domains].sort((a, b) => a.sequence - b.sequence)) {
  p(`### ${d.sequence}. ${d.title} (${d.tracks.join(', ')})`);
  p();
  for (const t of d.topics) {
    p(`**${t.title}**`);
    p();
    for (const k of t.concepts) {
      const s = conceptStatus(k.id, lessons);
      const lesson = lessons.find((l) => l.lesson.conceptIds.includes(k.id));
      const src = k.reviewerRef ? `reviewer ${k.reviewerRef.chapter}, p. ${k.reviewerRef.pages}` : 'not mapped to reviewer';
      p(`- [${s === 'complete' ? 'x' : ' '}] ${k.title} — ${ICON[s]}${lesson ? ` (lesson \`${lesson.lesson.id}\`)` : ''} — ${src}${k.tracks.length === 1 ? ` — ${k.tracks[0].toUpperCase()} only` : ''}`);
    }
    p();
  }
}
p('## Lessons');
p();
for (const l of lessons) {
  p(`### ${l.lesson.title} (\`${l.file}\`)`);
  p();
  p(`- Completeness check: ${l.validation.complete ? 'PASS' : 'FAIL'}`);
  p(`- Verification: ${l.lesson.verification.status}; human expert review: ${l.lesson.verification.humanExpertReview ? 'yes' : 'NO'}`);
  const c = l.lesson.claims;
  p(`- Claims: ${c.filter((x) => x.status === 'checked').length} checked, ${c.filter((x) => x.status === 'pending').length} pending, ${c.filter((x) => x.status === 'analogy').length} analogy`);
  p(`- Open accuracy flags: ${l.lesson.accuracyFlags.filter((f) => f.status === 'open').length}`);
  l.reviewNeeds.forEach((n) => p(`- Requires review: ${n}`));
  p();
}
p('## Exam track outline verification');
p();
for (const t of tracks) {
  p(`### ${t.name}`);
  p();
  t.outline.forEach((o) => p(`- ${o.verified ? '✅ verified' : '⚠️ UNVERIFIED'} — [${o.title}](${o.url}) (${o.checkedAt}): ${o.verificationNote}`));
  p();
  p('| Area | Weight | Weight verified |');
  p('|---|---|---|');
  t.areas.forEach((a) => p(`| ${a.name} | ${a.weight} | ${a.weightVerified ? 'yes' : 'NO'} |`));
  p();
}
writeFileSync(join(ROOT, 'docs/COVERAGE.md'), L.join('\n') + '\n');
console.log('wrote docs/COVERAGE.md');
