/**
 * Regenerates docs/COVERAGE.md from the content files so the checklist never drifts.
 * Usage: npm run coverage:report
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { conceptStatus, coverage } from '../src/logic/curriculum';
import { loadContent, ROOT } from './load-content';
import { formatLocation } from '../src/logic/locate';
import { readFileSync } from 'node:fs';

const { curriculum, tracks, reviewer, lessons } = loadContent();
const review = JSON.parse(readFileSync(join(ROOT, 'content/reviewer-review.json'), 'utf8')) as { statement: string; scan: { note: string }; flags: { id: string; status: string; kind: string; issue: string; location: { chapter: number; section: string; items?: number[] }; evidence: { citation: string; url?: string }[] }[] };
const L: string[] = [];
const p = (s = '') => L.push(s);
const ICON = { complete: '✅ complete', 'complete-needs-review': '🟡 complete — requires review', draft: '🟠 draft (incomplete)', pending: '⬜ pending' } as const;

p('# Curriculum coverage checklist');
p();
p('_Generated by `npm run coverage:report` from /content. Do not edit by hand._');
p();
p('## Source reviewer');
p();
p(`- Received: **${reviewer.received ? 'yes' : 'NO'}**${reviewer.title ? ` — *${reviewer.title}*, ${reviewer.author}, ${reviewer.edition}` : ''}`);
p(`- Accessible: ${reviewer.pagesAccessible ?? 'none'}`);
p(`- ${reviewer.statement}`);
if (reviewer.selfReportedReview) p(`- Reviewer's own review status: ${reviewer.selfReportedReview}`);
p();
if (reviewer.chapters.length) {
  p('| Chapter | High-Yield Hits | Tables | Exam Traps | Reviewer exam Qs | Concepts taught | Status |');
  p('|---|---|---|---|---|---|---|');
  reviewer.chapters.forEach((c) => {
    const t = curriculum.domains.flatMap((d) => d.topics).find((x) => x.reviewerChapter === c.n);
    const ks = t?.concepts ?? [];
    const taught = ks.filter((k) => conceptStatus(k.id, lessons).startsWith('complete')).length;
    const ls = lessons.filter((l) => l.validation.complete && l.lesson.conceptIds.some((id) => ks.some((k) => k.id === id))).map((l) => `\`${l.lesson.id}\``);
    const needsReview = ks.some((k) => conceptStatus(k.id, lessons) === 'complete-needs-review');
    const state = taught === 0 ? '⬜ not started' : taught < ks.length ? '🟡 in progress' : needsReview ? '🟡 all concepts taught — lessons require review' : '✅ complete';
    p(`| ${c.n}. ${c.title} | ${c.counts.highYield} | ${c.counts.tables} (${c.counts.tableRows} rows) | ${c.counts.traps} | ${c.counts.simulatorQuestions} | ${taught}/${ks.length} | ${state}${ls.length ? ` — ${ls.join(', ')}` : ''} |`);
  });
} else p('No reviewer chapters inventoried yet (reviewer not received).');
p();
p('## Reviewer accuracy register');
p();
p(review.statement);
p();
p(`Automated scan: ${review.scan.note}`);
p();
review.flags.forEach((f) => p(`- **${f.status}** · ${f.kind} · ${formatLocation(f.location)} — ${f.issue}${f.evidence.length ? ` _(evidence: ${f.evidence.map((e) => e.url ? `[${e.citation}](${e.url})` : e.citation).join('; ')})_` : ''}`));
p();
p('## Curriculum inventory');
p();
p(`- Provenance: **${curriculum.provenance.status}** — ${curriculum.provenance.statement}`);
p();
p('Legend: ✅ complete lesson · 🟡 complete lesson that still requires accuracy/expert review · 🟠 draft that fails the completeness check · ⬜ no lesson yet. Titles, placeholders and drafts are never counted as complete.');
p();
const all = coverage(curriculum, lessons, 'both');
const tot = all.reduce((a, d) => ({ total: a.total + d.total, complete: a.complete + d.complete, review: a.review + d.needsReview, draft: a.draft + d.draft, mapped: a.mapped + d.mappedToReviewer }), { total: 0, complete: 0, review: 0, draft: 0, mapped: 0 });
p(`**Totals:** ${tot.complete}/${tot.total} concepts have a complete lesson (${tot.review} of those require review); ${tot.draft} draft; ${tot.total - tot.complete - tot.draft} pending; ${tot.mapped} come from the reviewer (the rest are gap concepts the reviewer does not cover).`);
p();
p('| Domain | Concepts | Complete | Requires review | Draft | Pending | From reviewer |');
p('|---|---|---|---|---|---|---|');
all.forEach((d) => p(`| ${d.domain.title} | ${d.total} | ${d.complete} | ${d.needsReview} | ${d.draft} | ${d.pending} | ${d.mappedToReviewer} |`));
p();
for (const d of [...curriculum.domains].sort((a, b) => a.sequence - b.sequence)) {
  p(`### ${d.reviewerPart ? `Part ${d.reviewerPart} · ` : 'Not in reviewer · '}${d.title} (${d.tracks.join(', ')})`);
  if (d.notes) p(`_${d.notes}_`);
  p();
  for (const t of d.topics) {
    p(`**${t.title}**`);
    p();
    for (const k of t.concepts) {
      const s = conceptStatus(k.id, lessons);
      const lesson = lessons.find((l) => l.lesson.conceptIds.includes(k.id));
      const src = k.reviewerRef ? formatLocation(k.reviewerRef) : 'not in reviewer';
      p(`- [${s === 'complete' ? 'x' : ' '}] ${k.title} — ${ICON[s]}${lesson ? ` (lesson \`${lesson.lesson.id}\`)` : ''} — ${src}${k.tracks.length === 1 ? ` — ${k.tracks[0].toUpperCase()} only` : ''}`);
    }
    p();
  }
}
p('## Lessons');
p();
for (const l of lessons) {
  p(`### ${l.lesson.title} (\`${l.file}\`)`);
  p();
  p(`- Completeness check: ${l.validation.complete ? 'PASS' : 'FAIL'}`);
  p(`- Verification: ${l.lesson.verification.status}; human expert review: ${l.lesson.verification.humanExpertReview ? 'yes' : 'NO'}`);
  const c = l.lesson.claims;
  p(`- Claims: ${c.filter((x) => x.status === 'checked').length} checked, ${c.filter((x) => x.status === 'pending').length} pending, ${c.filter((x) => x.status === 'analogy').length} analogy`);
  p(`- Open accuracy flags: ${l.lesson.accuracyFlags.filter((f) => f.status === 'open').length}`);
  l.reviewNeeds.forEach((n) => p(`- Requires review: ${n}`));
  p();
}
p('## Exam track outline verification');
p();
for (const t of tracks) {
  p(`### ${t.name}`);
  p();
  t.outline.forEach((o) => p(`- ${o.verified ? '✅ verified' : '⚠️ UNVERIFIED'} — [${o.title}](${o.url}) (${o.checkedAt}): ${o.verificationNote}`));
  p();
  p('| Area | Weight | Weight verified |');
  p('|---|---|---|');
  t.areas.forEach((a) => p(`| ${a.name} | ${a.weight} | ${a.weightVerified ? 'yes' : 'NO'} |`));
  p();
}
writeFileSync(join(ROOT, 'docs/COVERAGE.md'), L.join('\n') + '\n');
console.log('wrote docs/COVERAGE.md');
